###########################   PROVIDER ROUTES   #################


### Registering Provider Account
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  	"name": "Harish",
   "email": "minnu158351@gmail.com",
   "password": "123456",
   "aadhaarNumber":123456289123,
   "gender":"male",
   "contactNumber":1234527891,
   "address":"chikkadpally hyderabad telangana",
   "role" : "Job-Provider" 
  }
###  Provider Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC43MTk3MDAyMjUzNzA4MjIyLCJpYXQiOjE1ODU3MjcwODN9.PwCK-HhsRWSQA94QC5e8zro8Q4nnhhr095KY6faxuyc?user=Job-Provider

### Logging into Provider Account
POST http://localhost:8080/api/user/login
Content-Type: application/json

 {  
   "email": "harishponna55@gmail.com",
   "password": "123456",   
   "role" : "Job-Provider" 
  }

### Posting a job by provider
POST http://localhost:8080/api/jobprovider/postingjob
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs

{
            "category":"weekly",
            "duration": 5,
            "title":"piano tutor",
            "description":"piano teaching for my kid",
            "preferedSkills":"pianist",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"pianist",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
        }

###  Showing provider his own posted jobs
GET http://localhost:8080/api/jobprovider/jobspostedtilldate/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs


###  Job updation by Provider Account
PATCH http://localhost:8080/api/jobprovider/udpatingjob/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs

{
            "category":"monthly",
            "duration": 2,
            "title":"paino tutor",
            "description":"paino teaching for my kid",
            "preferedSkills":"pianist",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"pianist",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
}


###  Job Deletion by Provider
DELETE http://localhost:8080/api/jobprovider/deletingjob/4/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs


###   Uploading Profile Picture
PATCH http://localhost:8080/api/jobprovider/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hari.jpeg"
Content-Type: image/jpeg

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### udpating profile
PATCH http://localhost:8080/api/jobprovider/editprofile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs

{
  "contactNumber" : 1234567892,
   "address" : "Bhupalpally abcdefghtikjjh"
}

### updating editing  password 
PATCH http://localhost:8080/api/jobprovider/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs

{
  "password":"123456"
}





###  Logging out from Provider Account
DELETE http://localhost:8080/api/jobprovider/logout/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI3MzYyLCJleHAiOjE1OTE3MjczNjJ9.BTHY0kqB-zeMF615fTq37yJxwD5jR1RS4zfnmm_Rdjs

### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"harishponna55@gmail.com",
  "role":"Job-Provider",
  "aadhaarNumber":123456789123
}


#######################################  SEEKER ROUTES   ###################################3


###   Register Seeker Account
POST http://localhost:8080/api/user/register
content-type: application/json

{
  	"name": "Siddhida",
    "email":"jhasiddhidda@gmail.com",
    "password":"123456",
   "aadhaarNumber" :123456789789,
  "gender":"female",
   "contactNumber" : 1234567897,
   "address" : "Ranchi abcdefghtikjjh",
   "role" : "Job-Seeker"
}

###  Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC4xMjIxNDY4MTIzODM0NzA1OCwiaWF0IjoxNTg1NzI4MTM5fQ.MVgMaykPymc9_qxHo5mhBvQxqs0xXYtKoibuQrQQcE0?user=Job-Seeker


###   Login into Seeker Account
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email":"jhasiddhidda@gmail.com",
    "password":"123456",
    "role":"Job-Seeker"
}

### showing all jobs which are available
GET http://localhost:8080/api/jobseeker/searchjobs/allavailablejobs/1/


### filtering jobs by category of hourly, daily, weekly, monthly

GET http://localhost:8080/api/jobseeker/searchjobs/filter/1?category=hourly


### showing single job by jobId
GET http://localhost:8080/api/jobseeker/searchjobs/byjobId/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc


###   Job Accepting by Seeker
PATCH http://localhost:8080/api/jobseeker/searchjobs/byjobid/1/isaccepted
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc


###  showing jobs accepted by seeker till date
GET http://localhost:8080/api/jobseeker/jobsacceptedtilldate/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc


###   Uploading Profile Picture
PATCH http://localhost:8080/api/jobseeker/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hari.jpeg"
Content-Type: image/jpeg

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### udpating profile
PATCH http://localhost:8080/api/jobseeker/editprofile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc

{
  "contactNumber" : 8977777077,
   "address" : "Ranchi abcdefghtikjjh"
}


##### Edit password
PATCH http://localhost:8080/api/jobseeker/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc

{
  "password":"123456"
}

###  Logging out from Seeker Account
DELETE http://localhost:8080/api/jobseeker/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzI5ODk0LCJleHAiOjE1OTE3Mjk4OTR9.BgkZba_07tOPkvH_lp0AIgCItDBDDlD1UsZSA5gVZzc

### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"jhasiddhidda@gmail.com",
  "role":"Job-Seeker",
  "aadhaarNumber":123456789789
}





######################### Admin Routes ###############################

### Loggin In

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password":"admin",
    "role":"Admin"
}

### view all available(including blocked) jobs
GET http://localhost:8080/api/admin/allavailablejobs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4

### view all accepted jobs
GET http://localhost:8080/api/admin/allacceptedjobs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4

### view all Providers
GET http://localhost:8080/api/admin/allproviders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4

### view all seekers
GET http://localhost:8080/api/admin/allseekers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4

### Blocking
PATCH http://localhost:8080/api/admin/1/isblocked/?model=Job   
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4

### logout
DELETE http://localhost:8080/api/admin/logout/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NzMxMjc3LCJleHAiOjE1OTE3MzEyNzd9.sYROB7e1bV0WC2mJrVZcizoPsF79q88UoAeW2ysVYe4