###########################   PROVIDER ROUTES   #################

################ GET

###  Provider Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC4yOTY1MDU1MTI3OTY5OTA2NywiaWF0IjoxNTg1NTc0MzkwfQ.MrnU1uXK0EHSF5BpT0Vxyeq-yPwuY5TENZ4zv7s165A?user=Job-Provider

###  Showing provider his own posted jobs
GET http://localhost:8080/api/jobprovider/jobspostedtilldate/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc0OTYzLCJleHAiOjE1OTE1NzQ5NjN9.RK43Yvt3hcJ8tkUYY9V7iq7qSRnx1mQ_enYFBUFyMws


################ POST

### Posting a job by provider
POST http://localhost:8080/api/jobprovider/postingjob
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc0OTYzLCJleHAiOjE1OTE1NzQ5NjN9.RK43Yvt3hcJ8tkUYY9V7iq7qSRnx1mQ_enYFBUFyMws

{
            "category":"hourly",
            "duration": 5,
            "title":"calendar tutor",
            "description":"calendar teaching for my kid",
            "preferedSkills":"musician",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"musician",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
        }
### Registering Provider Account
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  	"name": "Harish Ponna",
   "email": "harishponna55@gmail.com",
   "password": "123456",
   "aadhaarNumber":123456789789,
   "gender":"male",
   "contactNumber":1234567897,
   "address":"chikkadpally hyderabad telangana",
   "role" : "Job-Provider" 
  }


### Logging into Provider Account
POST http://localhost:8080/api/user/login
Content-Type: application/json

 {  
   "email": "harishponna55@gmail.com",
   "password": "11805549",   
   "role" : "Job-Provider" 
  }


### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"harishponna55@gmail.com",
  "role":"Job-Provider",
  "aadhaarNumber":123456789789
}
################ UPDATE

###   Uploading Profile Picture
POST http://localhost:8080/api/jobprovider/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTdkZDUyNDgzNTQxNjJjODRmYTc2ODEiLCJpYXQiOjE1ODUzMDUwMDMsImV4cCI6MTU4NTkwNTAwM30.0rOOqL0NZxJ8D-On6bhqBdyUS4zJche7XvfvSwYPKkU


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: multipart/form-data; name="image"; filename="1.png"
Content-Type: image/png

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###  Job updation by Provider Account
PATCH http://localhost:8080/api/jobprovider/udpatingjob/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTE1NzgyLCJleHAiOjE1OTE1MTU3ODJ9.VU17HbLo3Etxf4QAUVddrMD2gMBg32WZDxeOyzc5y_o

{
            "category":"yearly",
            "duration": 5,
            "title":"calendar tutor",
            "description":"calendar teaching for my kid",
            "preferedSkills":"musician",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"cricket",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
        }

### updating editing  password 
PATCH http://localhost:8080/api/jobprovider/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc0OTYzLCJleHAiOjE1OTE1NzQ5NjN9.RK43Yvt3hcJ8tkUYY9V7iq7qSRnx1mQ_enYFBUFyMws

{
  "password":"1234567890"
}



################ DELETE

###  Job Deletion by Provider
DELETE http://localhost:8080/api/jobprovider/deletingjob/4/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTY1MDM5LCJleHAiOjE1OTE1NjUwMzl9.yqt1IE8p8JUo5UZ6FJhGn-Kq0FIiKRVrSy9Ne_LlCMc

###  Logging out from Provider Account
DELETE http://localhost:8080/api/user/jobprovider/logout/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc0OTYzLCJleHAiOjE1OTE1NzQ5NjN9.RK43Yvt3hcJ8tkUYY9V7iq7qSRnx1mQ_enYFBUFyMws
